### ISSUE TITLE
可以使用inject的方式注入命令

### ISSUE THREAD

**Issue by hanxi** [lizijie/skynet_debug_console_enhance#1]
参考 https://github.com/hanxi/skynet-demo#%E6%97%A0%E4%BE%B5%E5%85%A5%E5%BC%8F%E6%89%A9%E5%B1%95%E5%AE%98%E6%96%B9%E7%9A%84-debug_console-%E6%9C%8D%E5%8A%A1

**Comment by lizijie** [comment]
> 参考 https://github.com/hanxi/skynet-demo#%E6%97%A0%E4%BE%B5%E5%85%A5%E5%BC%8F%E6%89%A9%E5%B1%95%E5%AE%98%E6%96%B9%E7%9A%84-debug_console-%E6%9C%8D%E5%8A%A1

这个我今天在你的skynet-demo也看了，我至少认为对于自己的需要，是可以改动skynet原本的代码，inject 的方式并不是必要
